[project]
name = "simon-says-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=3.2.0",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "plotly>=5.18.0",
    "numpy>=1.26.0",
]
